spring:
  application:
    name: central-system
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/central_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080

jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH:classpath:private.pem}

internal:
  api-key: ${INTERNAL_API_KEY:secret}
