package com.gameplatform.local.domain.model;

import java.time.Instant;
import java.util.Objects;

/**
 * Local persistence of an admin-request row written atomically with the
 * matching {@code OutboxEvent} (PIANO §7.B W6/W9/W10/W12). The
 * {@code requestId} doubles as both the {@code admin_requests_local}
 * PK and the outbox {@code eventId}: a single UUID is generated by the
 * W use case, used as the {@code eventId} of the outbox row and as the
 * {@code requestId} of the admin-request row, so the Central
 * return-event can carry it back as {@code originatingRequestId} and
 * the matching {@code *SyncService} can {@code markCompleted(requestId)}
 * on the local row.
 *
 * <p>Pure Java POJO, immutable, identity = {@code requestId}. The
 * {@code status} field is exposed as a {@link String} (rather than the
 * {@link AdminRequestStatus} enum) so the lifecycle state can be read
 * by adapters without forcing an enum parse on every read. Nullability:
 * {@code completedAt} and {@code outboxEventId} are nullable only at
 * the JPA column level because of the schema's relaxed NULL contract,
 * but for an admin-request persisted by a W use case they are always
 * non-null: {@code outboxEventId} equals {@code requestId} (the row is
 * atomic with the outbox insert), and {@code completedAt} is filled in
 * by the {@code markCompleted} state transition.</p>
 */
public class AdminRequestLocal {

    private final String requestId;
    private final String eventType;
    private final String actingUserId;
    private final String actingRole;
    private final String buildingId;
    private final String payloadJson;
    private final String status;
    private final String resultDataJson;
    private final Instant createdAt;
    private final Instant completedAt;
    private final String outboxEventId;

    public AdminRequestLocal(String requestId, String eventType, String actingUserId, String actingRole,
                             String buildingId, String payloadJson, String status, String resultDataJson,
                             Instant createdAt, Instant completedAt, String outboxEventId) {
        if (requestId == null || requestId.isBlank()) {
            throw new IllegalArgumentException("requestId cannot be blank");
        }
        if (eventType == null || eventType.isBlank()) {
            throw new IllegalArgumentException("eventType cannot be blank");
        }
        if (actingUserId == null || actingUserId.isBlank()) {
            throw new IllegalArgumentException("actingUserId cannot be blank");
        }
        if (status == null || status.isBlank()) {
            throw new IllegalArgumentException("status cannot be blank");
        }
        if (createdAt == null) {
            throw new IllegalArgumentException("createdAt cannot be null");
        }
        this.requestId = requestId;
        this.eventType = eventType;
        this.actingUserId = actingUserId;
        this.actingRole = actingRole;
        this.buildingId = buildingId;
        this.payloadJson = payloadJson;
        this.status = status;
        this.resultDataJson = resultDataJson;
        this.createdAt = createdAt;
        this.completedAt = completedAt;
        this.outboxEventId = outboxEventId;
    }

    public String getRequestId() {
        return requestId;
    }

    public String getEventType() {
        return eventType;
    }

    public String getActingUserId() {
        return actingUserId;
    }

    public String getActingRole() {
        return actingRole;
    }

    public String getBuildingId() {
        return buildingId;
    }

    public String getPayloadJson() {
        return payloadJson;
    }

    public String getStatus() {
        return status;
    }

    public String getResultDataJson() {
        return resultDataJson;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    public String getOutboxEventId() {
        return outboxEventId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AdminRequestLocal that = (AdminRequestLocal) o;
        return Objects.equals(requestId, that.requestId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(requestId);
    }
}
