package com.gameplatform.local.domain.model;

import java.time.Instant;
import java.util.Objects;

/**
 * Local persistence of an admin-request row written atomically with the
 * matching {@code OutboxEvent} (PIANO §7.B W6/W9/W10/W12). The
 * {@code requestId} doubles as both the {@code admin_requests_local}
 * PK and the outbox {@code eventId}: a single UUID is generated by the
 * W use case, used as the {@code eventId} of the outbox row and as the
 * {@code requestId} of the admin-request row, so the Central
 * return-event can carry it back as {@code originatingRequestId} and
 * the matching {@code *SyncService} can {@code markCompleted(requestId)}
 * on the local row.
 *
 * <p>Pure Java POJO, immutable, identity = {@code requestId}. The
 * {@code status} field is exposed as a {@link String} (rather than the
 * {@link AdminRequestStatus} enum) so the lifecycle state can be read
 * by adapters without forcing an enum parse on every read. Nullability:
 * {@code completedAt} and {@code outboxEventId} are nullable only at
 * the JPA column level because of the schema's relaxed NULL contract,
 * but for an admin-request persisted by a W use case they are always
 * non-null: {@code outboxEventId} equals {@code requestId} (the row is
 * atomic with the outbox insert), and {@code completedAt} is filled in
 * by the {@code markCompleted} state transition.</p>
 */
public class AdminRequestLocal {

    private final String requestId;
    private final String eventType;
    private final String actingUserId;
    private final String actingRole;
    private final String buildingId;
    private final String payloadJson;
    private final String status;
    private final String resultDataJson;
    private final Instant createdAt;
    private final Instant completedAt;
    private final String outboxEventId;

    /**
     * Costruisce una nuova richiesta amministrativa locale.
     *
     * @param requestId      identificatore univoco della richiesta (non blank)
     * @param eventType      tipo di evento associato (non blank)
     * @param actingUserId   identificatore dell'utente che ha effettuato la richiesta (non blank)
     * @param actingRole     ruolo dell'utente richiedente
     * @param buildingId     identificatore dell'edificio coinvolto
     * @param payloadJson    payload JSON della richiesta
     * @param status         stato corrente della richiesta (non blank)
     * @param resultDataJson dati JSON del risultato (può essere null)
     * @param createdAt      istante di creazione (non null)
     * @param completedAt    istante di completamento (può essere null)
     * @param outboxEventId  identificatore dell'evento outbox associato
     * @throws IllegalArgumentException se requestId, eventType, actingUserId o status sono blank, o createdAt è null
     */
    public AdminRequestLocal(String requestId, String eventType, String actingUserId, String actingRole,
                             String buildingId, String payloadJson, String status, String resultDataJson,
                             Instant createdAt, Instant completedAt, String outboxEventId) {
        if (requestId == null || requestId.isBlank()) {
            throw new IllegalArgumentException("requestId cannot be blank");
        }
        if (eventType == null || eventType.isBlank()) {
            throw new IllegalArgumentException("eventType cannot be blank");
        }
        if (actingUserId == null || actingUserId.isBlank()) {
            throw new IllegalArgumentException("actingUserId cannot be blank");
        }
        if (status == null || status.isBlank()) {
            throw new IllegalArgumentException("status cannot be blank");
        }
        if (createdAt == null) {
            throw new IllegalArgumentException("createdAt cannot be null");
        }
        this.requestId = requestId;
        this.eventType = eventType;
        this.actingUserId = actingUserId;
        this.actingRole = actingRole;
        this.buildingId = buildingId;
        this.payloadJson = payloadJson;
        this.status = status;
        this.resultDataJson = resultDataJson;
        this.createdAt = createdAt;
        this.completedAt = completedAt;
        this.outboxEventId = outboxEventId;
    }

    /**
     * Restituisce l'identificatore univoco della richiesta.
     *
     * @return requestId
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Restituisce il tipo di evento associato.
     *
     * @return eventType
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Restituisce l'identificatore dell'utente richiedente.
     *
     * @return actingUserId
     */
    public String getActingUserId() {
        return actingUserId;
    }

    /**
     * Restituisce il ruolo dell'utente richiedente.
     *
     * @return actingRole
     */
    public String getActingRole() {
        return actingRole;
    }

    /**
     * Restituisce l'identificatore dell'edificio coinvolto.
     *
     * @return buildingId
     */
    public String getBuildingId() {
        return buildingId;
    }

    /**
     * Restituisce il payload JSON della richiesta.
     *
     * @return payloadJson
     */
    public String getPayloadJson() {
        return payloadJson;
    }

    /**
     * Restituisce lo stato corrente della richiesta.
     *
     * @return status
     */
    public String getStatus() {
        return status;
    }

    /**
     * Restituisce i dati JSON del risultato.
     *
     * @return resultDataJson, o null se non ancora completata
     */
    public String getResultDataJson() {
        return resultDataJson;
    }

    /**
     * Restituisce l'istante di creazione della richiesta.
     *
     * @return createdAt
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Restituisce l'istante di completamento della richiesta.
     *
     * @return completedAt, o null se non ancora completata
     */
    public Instant getCompletedAt() {
        return completedAt;
    }

    /**
     * Restituisce l'identificatore dell'evento outbox associato.
     *
     * @return outboxEventId
     */
    public String getOutboxEventId() {
        return outboxEventId;
    }

    /**
     * Confronta questa richiesta con un altro oggetto per uguaglianza basata su requestId.
     *
     * @param o l'oggetto da confrontare
     * @return true se gli oggetti sono uguali
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AdminRequestLocal that = (AdminRequestLocal) o;
        return Objects.equals(requestId, that.requestId);
    }

    /**
     * Restituisce l'hash code basato su requestId.
     *
     * @return hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(requestId);
    }
}
