@startuml
actor PLAYER as "Player"
actor GameClient as "Game Client"
actor MqttBroker as "MQTT Broker"
(Prenota postazione di gioco) as UC1
(Avvia sessione di gioco) as UC2
(Metti in pausa/riprendi sessione) as UC3
(Termina sessione con risultato) as UC4
PLAYER --> UC1
PLAYER --> UC2
PLAYER --> UC3
PLAYER --> UC4
GameClient --> UC1
GameClient --> UC2
GameClient --> UC3
GameClient --> UC4
MqttBroker --> UC2
MqttBroker --> UC3
MqttBroker --> UC4
@enduml