package com.gameplatform.central.application.service;

import com.gameplatform.central.domain.exception.InvalidTournamentStateException;
import com.gameplatform.central.domain.exception.TournamentNotFoundException;
import com.gameplatform.central.domain.model.Tournament;
import com.gameplatform.central.domain.model.TournamentMatch;
import com.gameplatform.central.domain.model.TournamentParticipant;
import com.gameplatform.central.domain.ports.in.ListTournamentMatchesUseCase;
import com.gameplatform.central.domain.ports.in.ScheduleTournamentMatchesUseCase;
import com.gameplatform.central.domain.ports.out.TournamentMatchOutboxPort;
import com.gameplatform.central.domain.ports.out.TournamentMatchRepository;
import com.gameplatform.central.domain.ports.out.TournamentParticipantRepository;
import com.gameplatform.central.domain.ports.out.TournamentRepository;
import com.gameplatform.shared.domain.model.TournamentFormat;
import com.gameplatform.shared.domain.model.TournamentId;
import com.gameplatform.shared.domain.model.TournamentMatchId;
import com.gameplatform.shared.domain.model.TournamentMatchStatus;
import com.gameplatform.shared.domain.model.TournamentStatus;
import com.gameplatform.shared.dto.TournamentMatchDto;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Application service that builds the round-1 single-elimination bracket for a
 * tournament and lists the matches of a tournament.
 *
 * <p>Single-elimination bracket construction for an {@code OPEN_REGISTRATION}
 * tournament. Atomic outbox emission per SCHEDULED match (Outbox Pattern, mirroring
 * {@code LocalAdminBuildingService.writeOutboxEvent}).
 *
 * <p><b>Top-seeds-get-byes convention</b>: participants sorted by {@code registeredAt}
 * ASC. Top {@code byes = nextPow2(N) - N} seeds (earliest registered) get BYE rows in
 * round 1. Remaining {@code N - byes} participants pair: lowest remaining seed
 * (earliest registered among non-byes) vs highest remaining seed (latest registered
 * among non-byes).
 *
 * <p><b>BYE row semantics</b>: {@code participantB = null}, {@code status = BYE},
 * {@code winner = participantA}. BYE rows are persisted for bracket completeness but
 * NEVER emitted via the outbox — they are auto-advancements, not matches to be played
 * at a building; FASE 6 only needs {@code TOURNAMENT_MATCH_SCHEDULED} events for
 * genuine SCHEDULED round-1 games.
 *
 * <p><b>Bracket size and rounds</b>: {@code bracketSize = nextPow2(N)},
 * {@code rounds = log2(bracketSize)}. FASE 5 only persists round-1 matches; subsequent
 * rounds are generated by FASE 6 {@code advanceWinner} as winners become known.
 *
 * <p><b>Idempotency-by-rejection</b>: {@code Tournament.startProgress()} only allows
 * {@code OPEN_REGISTRATION -> IN_PROGRESS}, so a second {@code /schedule} call on an
 * already-{@code IN_PROGRESS} tournament throws {@link InvalidTournamentStateException}
 * (HTTP 400).
 *
 * <p><b>Minimum 2 participants</b>: throws {@link InvalidTournamentStateException} if
 * fewer than 2.
 *
 * <p><b>Format guard</b>: only {@link TournamentFormat#SINGLE_ELIMINATION} is
 * supported in FASE 5; {@link TournamentFormat#ROUND_ROBIN} is RF-TO-13 Could-Have,
 * deferred to a later phase.
 */
@Service
@Transactional
public class TournamentBracketService implements ScheduleTournamentMatchesUseCase, ListTournamentMatchesUseCase {

    private static final Logger log = LoggerFactory.getLogger(TournamentBracketService.class);

    private final TournamentRepository tournamentRepository;
    private final TournamentParticipantRepository tournamentParticipantRepository;
    private final TournamentMatchRepository tournamentMatchRepository;
    private final TournamentMatchOutboxPort tournamentMatchOutboxPort;
    private final TournamentStandingsService tournamentStandingsService;
    private final Clock clock;

    public TournamentBracketService(TournamentRepository tournamentRepository,
                                    TournamentParticipantRepository tournamentParticipantRepository,
                                    TournamentMatchRepository tournamentMatchRepository,
                                    TournamentMatchOutboxPort tournamentMatchOutboxPort,
                                    TournamentStandingsService tournamentStandingsService,
                                    Clock clock) {
        this.tournamentRepository = tournamentRepository;
        this.tournamentParticipantRepository = tournamentParticipantRepository;
        this.tournamentMatchRepository = tournamentMatchRepository;
        this.tournamentMatchOutboxPort = tournamentMatchOutboxPort;
        this.tournamentStandingsService = tournamentStandingsService;
        this.clock = clock;
    }

    /**
     * Build the round-1 single-elimination bracket for the given tournament, transition
     * it to {@code IN_PROGRESS}, persist every round-1 match (BYE rows and SCHEDULED
     * rows), emit a {@code TOURNAMENT_MATCH_SCHEDULED} outbox event for each SCHEDULED
     * match, seed the standings for all participants, and return the generated matches
     * ordered by {@code bracketPosition}.
     *
     * @param tournamentId id of the tournament to schedule (must not be null)
     * @return the round-1 matches (BYE + SCHEDULED) ordered by {@code bracketPosition}
     * @throws IllegalArgumentException       if {@code tournamentId} is null
     * @throws TournamentNotFoundException   if no such tournament exists
     * @throws InvalidTournamentStateException if the tournament format is not
     *     {@code SINGLE_ELIMINATION}, if the tournament is not in
     *     {@code OPEN_REGISTRATION} state, or if it has fewer than 2 participants
     */
    @Override
    public List<TournamentMatchDto> schedule(TournamentId tournamentId) {
        if (tournamentId == null) {
            throw new IllegalArgumentException("tournamentId cannot be null");
        }

        // 1. Load tournament or 404.
        Tournament tournament = tournamentRepository.findById(tournamentId)
                .orElseThrow(() -> new TournamentNotFoundException("Tournament not found: " + tournamentId.value()));

        // 2. Format guard: only SINGLE_ELIMINATION is implemented in FASE 5.
        if (tournament.getFormat() != TournamentFormat.SINGLE_ELIMINATION) {
            throw new InvalidTournamentStateException(
                    "Tournament format " + tournament.getFormat() + " is not supported (only SINGLE_ELIMINATION)");
        }

        // 3. Status transition OPEN_REGISTRATION -> IN_PROGRESS (throws InvalidTournamentStateException
        //    if not OPEN_REGISTRATION; this gives us idempotency-by-rejection for free - a second
        //    /schedule call on an already-IN_PROGRESS tournament throws 400).
        Tournament inProgress = tournament.startProgress();
        tournamentRepository.save(inProgress);

        // 4. Load participants and SORT by registeredAt ASC for deterministic seeding.
        //    TournamentParticipantRepository.findByTournament has no explicit ORDER BY clause
        //    (verified at TournamentParticipantJpaRepository line 19), so we MUST sort here.
        List<TournamentParticipant> participants = tournamentParticipantRepository.findByTournament(tournamentId)
                .stream()
                .sorted(Comparator.comparing(TournamentParticipant::getRegisteredAt))
                .toList();

        int n = participants.size();
        if (n < 2) {
            throw new InvalidTournamentStateException(
                    "Cannot schedule a bracket with fewer than 2 participants (got " + n + ")");
        }

        int bracketSize = nextPow2(n);    // smallest power of 2 >= n
        int byes = bracketSize - n;       // number of auto-advancers in round 1
        int scheduledCount = (n - byes) / 2;  // = bracketSize/2 - byes
        // Total round-1 slots = bracketSize / 2 = byes + scheduledCount

        List<TournamentMatch> generated = new ArrayList<>();

        // 5. BYE rows: top `byes` seeds (first `byes` participants in registration order)
        //    auto-advance. BYE rows are persisted (so the bracket is complete) but do NOT
        //    emit an outbox event - they are not "scheduled for play at a building" and
        //    thus are not replicated to Local in FASE 6.
        int bracketPos = 1;
        for (int i = 0; i < byes; i++) {
            TournamentParticipant p = participants.get(i);
            TournamentMatch bye = new TournamentMatch(
                    new TournamentMatchId(UUID.randomUUID().toString()),
                    tournamentId,
                    1,
                    bracketPos++,
                    p.getParticipantId(),
                    null,                // participantB null => BYE
                    null, null, null,    // buildingId, gameId, sessionId
                    p.getParticipantId(), // winner = participantA (advancement)
                    TournamentMatchStatus.BYE,
                    null, null, null);   // scheduledAt, playedAt, resultData
            TournamentMatch saved = tournamentMatchRepository.save(bye);
            generated.add(saved);
            // NO outbox emission for BYE rows.
        }

        // 6. SCHEDULED rows: remaining (n - byes) seeds pair up so the lowest remaining
        //    seed (earliest-registered among non-byes = best seed remaining) plays the
        //    highest remaining seed (latest-registered = worst seed remaining), and so on.
        //    This is the standard single-elimination pairing convention.
        int firstScheduledIndex = byes;     // index in `participants`
        int lastScheduledIndex = n - 1;
        for (int j = 0; j < scheduledCount; j++) {
            TournamentParticipant pA = participants.get(firstScheduledIndex + j);   // best remaining
            TournamentParticipant pB = participants.get(lastScheduledIndex - j);     // worst remaining
            TournamentMatch match = new TournamentMatch(
                    new TournamentMatchId(UUID.randomUUID().toString()),
                    tournamentId,
                    1,
                    bracketPos++,
                    pA.getParticipantId(),
                    pB.getParticipantId(),
                    null, null, null, null,                 // buildingId, gameId, sessionId, winner
                    TournamentMatchStatus.SCHEDULED,
                    null, null, null);                       // scheduledAt, playedAt, resultData
            TournamentMatch saved = tournamentMatchRepository.save(match);
            tournamentMatchOutboxPort.publishScheduled(saved, inProgress);   // emit only for SCHEDULED
            generated.add(saved);
        }

        // 7. Seed zero-init standings for ALL participants (including BYE auto-advancers).
        //    The seed is idempotent (skips rows already present) and runs inside the same tx.
        List<String> allParticipantIds = participants.stream()
                .map(TournamentParticipant::getParticipantId)
                .toList();
        tournamentStandingsService.seedStandings(tournamentId, allParticipantIds);

        // 8. Return all generated matches (BYE + SCHEDULED) as DTOs ordered by bracketPosition.
        return generated.stream()
                .sorted(Comparator.comparing(TournamentMatch::getBracketPosition))
                .map(this::toDto)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public List<TournamentMatchDto> findByTournament(TournamentId tournamentId) {
        if (tournamentId == null) {
            return List.of();
        }
        return tournamentMatchRepository.findByTournament(tournamentId).stream()
                .map(this::toDto)
                .toList();
    }

    private TournamentMatchDto toDto(TournamentMatch m) {
        return new TournamentMatchDto(
                m.getMatchId().value(),
                m.getRound(),
                m.getBracketPosition(),
                m.getParticipantA(),
                m.getParticipantB(),
                m.getBuildingId(),
                m.getGameId(),
                m.getStatus(),
                m.getScheduledAt(),
                m.getWinner());
    }

    private static int nextPow2(int n) {
        int p = 1;
        while (p < n) {
            p <<= 1;
        }
        return p;
    }

    /**
     * Advances the winner of a completed match into the parent slot of the
     * next round. The match row itself is already updated (status/winner/
     * playedAt) by {@code SyncEventProcessor.handleTournamentMatchCompleted}
     * before this is called, so this method ONLY computes the parent and
     * patches the slot.
     *
     * <p>parentRound = round + 1; parentBracketPosition =
     * (bracketPosition + 1) / 2. Total rounds = log2(nextPow2(N)) where N =
     * participant count. If parentRound > totalRounds → return {@code null}
     * (the completed match IS the final — caller invokes {@link #completeIfDone}).
     * Otherwise, parent is loaded via
     * {@code tournamentMatchRepository.findByTournamentIdAndRoundAndBracketPositionForUpdate(...)}.
     * If the parent does not exist → CREATE it with participantA=winner,
     * participantB=null, status=SCHEDULED (the first winner fills slot A).
     * If the parent exists → patch the empty slot (participantA if null, else
     * participantB) with the winner. If the parent is now fully populated
     * (participantA != null AND participantB != null) → call
     * {@code tournamentMatchOutboxPort.publishScheduled(parent, tournament)} to
     * emit a new {@code TOURNAMENT_MATCH_SCHEDULED} outbox row. Return the
     * parent.</p>
     *
     * <p>Q2 resolution: {@code winnerId} is normally non-null (the Local side
     * sends the walkover winner even for ABANDONED matches). As a defensive
     * fallback, when {@code winnerId == null}: if {@code participantB} is null
     * (BYE-like, no opponent) → advance {@code participantA}; if both
     * participants are present but no winner was resolved → skip parent
     * patching and return {@code null}.</p>
     *
     * @param matchId  the completed match id
     * @param winnerId the winner participant id (normally non-null per Q2)
     * @return the parent match, or {@code null} if the completed match was the
     *         final (no parent round) or no winner could be resolved
     */
    public TournamentMatch advanceWinner(TournamentMatchId matchId, String winnerId) {
        if (matchId == null) {
            return null;
        }
        TournamentMatch match = tournamentMatchRepository.findById(matchId)
                .orElseThrow(() -> new TournamentNotFoundException("Match not found: " + matchId.value()));

        // Q2: resolve the effective winner (normally winnerId is non-null).
        String effectiveWinner = winnerId;
        if (effectiveWinner == null) {
            if (match.getParticipantB() == null) {
                // BYE-like (no opponent) → advance participantA.
                effectiveWinner = match.getParticipantA();
            } else {
                // Both participants present but no winner resolved — skip advancement.
                log.warn("advanceWinner: matchId={} has no winner and both participants present — skipping parent patching.",
                        matchId.value());
                return null;
            }
        }

        int parentRound = match.getRound() + 1;
        int parentBracketPosition = (match.getBracketPosition() + 1) / 2;

        // Compute total rounds from participant count to decide if this match IS the final.
        long n = tournamentParticipantRepository.countByTournament(match.getTournamentId());
        int bracketSize = nextPow2((int) n);
        int totalRounds = 31 - Integer.numberOfLeadingZeros(bracketSize);
        if (parentRound > totalRounds) {
            return null; // this match was the final — tournament completion signal
        }

        Optional<TournamentMatch> parentOpt = tournamentMatchRepository
                .findByTournamentIdAndRoundAndBracketPositionForUpdate(
                        match.getTournamentId(), parentRound, parentBracketPosition);

        TournamentMatch savedParent;
        if (parentOpt.isEmpty()) {
            // Create the parent match with the winner in participantA (first completion fills slot A).
            TournamentMatch newParent = new TournamentMatch(
                    new TournamentMatchId(UUID.randomUUID().toString()),
                    match.getTournamentId(), parentRound, parentBracketPosition,
                    effectiveWinner, null,
                    null, null, null, null,
                    TournamentMatchStatus.SCHEDULED,
                    null, null, null);
            savedParent = tournamentMatchRepository.save(newParent);
            // Only one participant — not ready to schedule yet (no outbox emission).
        } else {
            TournamentMatch parent = parentOpt.get();
            // Patch the FIRST empty slot (participantA if null, else participantB).
            String newParticipantA = parent.getParticipantA();
            String newParticipantB = parent.getParticipantB();
            if (newParticipantA == null) {
                newParticipantA = effectiveWinner;
            } else {
                newParticipantB = effectiveWinner;
            }

            TournamentMatch patchedParent = new TournamentMatch(
                    parent.getMatchId(), parent.getTournamentId(),
                    parent.getRound(), parent.getBracketPosition(),
                    newParticipantA, newParticipantB,
                    parent.getBuildingId(), parent.getGameId(), parent.getSessionId(),
                    parent.getWinner(), parent.getStatus(),
                    parent.getScheduledAt(), parent.getPlayedAt(), parent.getResultData());
            savedParent = tournamentMatchRepository.save(patchedParent);

            // If the parent is now fully populated, emit a scheduled outbox event for it.
            if (savedParent.getParticipantA() != null && savedParent.getParticipantB() != null) {
                Tournament tournament = tournamentRepository.findById(match.getTournamentId())
                        .orElseThrow(() -> new TournamentNotFoundException(
                                "Tournament not found: " + match.getTournamentId().value()));
                tournamentMatchOutboxPort.publishScheduled(savedParent, tournament);
            }
        }

        return savedParent;
    }

    /**
     * Completes the tournament if all matches are terminal (COMPLETED /
     * ABANDONED / BYE — no SCHEDULED or IN_PROGRESS remaining). Loads the
     * tournament via {@code tournamentRepository.findByIdForUpdate(...)};
     * if status is already COMPLETED → no-op; else if all matches are
     * terminal → {@code tournament.complete(Instant.now(clock))} + save, then
     * {@code tournamentStandingsService.assignFinalRanks(tournamentId)}.
     *
     * @param tournamentId the tournament id (no-op if null or absent)
     */
    public void completeIfDone(TournamentId tournamentId) {
        if (tournamentId == null) {
            return;
        }
        Optional<Tournament> tournamentOpt = tournamentRepository.findByIdForUpdate(tournamentId);
        if (tournamentOpt.isEmpty()) {
            return;
        }
        Tournament tournament = tournamentOpt.get();
        if (tournament.getStatus() == TournamentStatus.COMPLETED) {
            return;
        }
        List<TournamentMatch> matches = tournamentMatchRepository.findByTournament(tournamentId);
        boolean anyPending = matches.stream().anyMatch(m ->
                m.getStatus() == TournamentMatchStatus.SCHEDULED
                        || m.getStatus() == TournamentMatchStatus.IN_PROGRESS);
        if (anyPending) {
            return;
        }
        Tournament completed = tournament.complete(Instant.now(clock));
        tournamentRepository.save(completed);
        tournamentStandingsService.assignFinalRanks(tournamentId);
    }
}
